services:
  app:
    tty: true
    stdin_open: true
    build: .
    volumes:
      - .:/var/www/internship_test_questions/current
    command: bundle exec rails server --port=3000 --binding='0.0.0.0'
    ports:
      - 6002:3000
    restart: always
